# Generated by Django 3.0.6 on 2020-05-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_cat',
        ),
    ]
