# Generated by Django 3.0.6 on 2020-05-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200528_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_postTitle', models.CharField(max_length=200)),
                ('ap_postPost', models.TextField()),
                ('ap_postDateTime', models.DateTimeField(auto_now_add=True)),
                ('ap_postAuthor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_cat',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='tbl_adminpost',
            name='post_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.tbl_category'),
        ),
    ]
