# Generated by Django 3.0.6 on 2020-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200529_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_adminpost',
            name='ap_postImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
